export const GET_TOKENS = 'GET_TOKENS'
export const TOKENS_UPDATED = 'TOKENS_UPDATED'

// export const GET_FEES = 'GET_FEES'
// export const FEES_UPDATED = 'FEES_UPDATED'

export const SWAP_TOKEN = 'SWAP_TOKEN'
export const TOKEN_SWAPPED = 'TOKEN_SWAPPED'

export const FINALIZE_SWAP_TOKEN = 'FINALIZE_SWAP_TOKEN'
export const TOKEN_SWAP_FINALIZED = 'TOKEN_SWAP_FINALIZED'

export const TOKEN_SWAP_B2E = 'TOKEN_SWAP_B2E'
export const TOKEN_SWAPPED_B2E = 'TOKEN_SWAPPED_B2E'

export const TOKEN_SWAP_FINALIZE_B2E = 'TOKEN_SWAP_FINALIZ_B2E'
export const TOKEN_SWAP_FINALIZED_B2E = 'TOKEN_SWAP_FINALIZED_B2E'

export const GET_BNB_BALANCES = 'GET_BNB_BALANCES'
export const BNB_BALANCES_UPDATED = 'BNB_BALANCES_UPDATED'

export const GET_ETH_BALANCES = 'GET_ETH_BALANCES'
export const ETH_BALANCES_UPDATED = 'ETH_BALANCES_UPDATED'

export const GET_ERC20_INFO = 'GET_ERC20_INFO'
export const ERC20_INFO_UPDATED = 'ERC20_INFO_UPDATED'

export const ERROR = 'ERROR'
